better error handling

diff --git a/bin/clear_measurement b/bin/clear_measurement
--- a/bin/clear_measurement
+++ b/bin/clear_measurement
@@ -4,11 +4,11 @@
 #
 # Clear a measurement from influx bucket "Measurements"
 #/////////////////////////////////////////////////////////////////////////////////////
-MEASUREMENT="$1"
+MEASUREMENT=$1
 
-if [[ -n "${MEASUREMENT}" ]]; then
+if [[ -n $MEASUREMENT ]]; then
 
-	curl --request POST "${INFLUXDB_HOST}/api/v2/delete?org=${INFLUXDB_ORG}&bucket=${INFLUXDB_BUCKET_MEASUREMENTS}" \
+	status=$(curl --request POST "${INFLUXDB_HOST}/api/v2/delete?org=${INFLUXDB_ORG}&bucket=${INFLUXDB_BUCKET_MEASUREMENTS}" \
 	--header "Authorization: Token ${INFLUXDB_TOKEN}" \
 	--header "Content-Type: application/json" \
 	--data '{
@@ -16,6 +16,15 @@ if [[ -n "${MEASUREMENT}" ]]; then
 		"stop": "'"$(date --utc +"%Y-%m-%dT%H:%M:%SZ")"'",
 		"predicate": "_measurement=\"'"${MEASUREMENT}"'\""
 	}'
+	)
 
-	[[ $LOG_EXEC ]] && echo -e "${LOG_SUCC} Nanohome: Measurement \"${MEASUREMENT}\" cleared" >> /proc/1/fd/1
+	# Check if this was successfull
+	if [ "$upload_status" -eq 200 ] || [ "$upload_status" -eq 202 ]; then
+		echo -e "${LOG_SUCC} Nanohome: Measurement \"${MEASUREMENT}\" cleared" >> /proc/1/fd/1
+		exit 0
+	else
+		echo -e "${LOG_ERRO} Nanohome: Failed to clear measurement \"${MEASUREMENT}\"" >> /proc/1/fd/1
+		echo -e "${LOG_ERRO}  > status code: $upload_status" >> /proc/1/fd/1
+		exit 1
+	fi
 fi
