Revert "no idea..."
This reverts commit 0dbc28ecb35ec4c15d27b491a144cbecaa299c6c.

diff --git a/usr/local/nanohome/bin/autohotspot b/usr/local/nanohome/bin/autohotspot
--- a/usr/local/nanohome/bin/autohotspot
+++ b/usr/local/nanohome/bin/autohotspot
@@ -1,10 +1,15 @@
 #!/bin/bash
-#/////////////////////////////////////////////////////////////////////////////////////
-# Modified autohotspot script from RaspberryConnect.com 
-#/////////////////////////////////////////////////////////////////////////////////////
+#version 0.95-4-N/HS
 
-# Settings
-wifidev="wlan0"
+#You may share this script on the condition a reference to RaspberryConnect.com 
+#must be included in copies or derivatives of this script. 
+
+#A script to switch between a wifi network and a non internet routed Hotspot
+#Works at startup or with a seperate timer or manually without a reboot
+#Other setup required find out more at
+#http://www.raspberryconnect.com
+
+wifidev="wlan0" #device name to use. Default is wlan0.
 
 #use the command: iw dev ,to see wifi interface name 
 
@@ -16,110 +21,62 @@ IFS=","
 ssids=($wpassid)
 IFS=$IFSdef #reset back to defaults
 
+
+#Note:If you only want to check for certain SSIDs
+#Remove the # in in front of ssids=('mySSID1'.... below and put a # infront of all four lines above
+# separated by a space, eg ('mySSID1' 'mySSID2')
+#ssids=('mySSID1' 'mySSID2' 'mySSID3')
+
 #Enter the Routers Mac Addresses for hidden SSIDs, seperated by spaces ie 
 #( '11:22:33:44:55:66' 'aa:bb:cc:dd:ee:ff' ) 
 mac=()
 
 ssidsmac=("${ssids[@]}" "${mac[@]}") #combines ssid and MAC for checking
 
-
-#/////////////////////////////////////////////////////////////////////////////////////
-# Create Hotspot
-#/////////////////////////////////////////////////////////////////////////////////////
 createAdHocNetwork()
 {
-
-	ip link set dev "$wifidev" down
-	wpa_cli terminate >/dev/null 2>&1
-	ip addr flush "$wifidev"  
-	rm -r /var/run/wpa_supplicant >/dev/null 2>&1
-	
-	echo "[$(date +'%H:%m:%S')] Wifi disconnected" >> /var/log/autohotspot.log
-	
-	ip a add 10.0.0.5/24 brd + dev "$wifidev"
-	ip link set dev "$wifidev" up
-	
-	systemctl unmask dnsmasq hostapd
-	systemctl start dnsmasq hostapd
-	
-	echo "[$(date +'%H:%m:%S')] Hotspot created" >> /var/log/autohotspot.log
-  
+  ifdown "$wifidev"
+  wpa_cli terminate >/dev/null 2>&1
+  ip addr flush "$wifidev"
+  rm -r /var/run/wpa_supplicant >/dev/null 2>&1
+  ip a add 10.0.0.5/24 brd + dev "$wifidev"
+  ip link set dev "$wifidev" up
+  systemctl unmask dnsmasq
+  systemctl unmask hostapd
+  systemctl start dnsmasq
+  systemctl start hostapd
+  ip_to_mqtt
+  echo "Hotspot created"
 }
 
-#/////////////////////////////////////////////////////////////////////////////////////
-# Kill Hotspot
-#/////////////////////////////////////////////////////////////////////////////////////
 KillHotspot()
 {
-
-	echo "[$(date +'%H:%m:%S')] Shutting Down Hotspot" >> /var/log/autohotspot.log
-	ip link set dev "$wifidev" down
-	
-	systemctl stop hostapd dnsmasq
-	systemctl mask dnsmasq hostapd
-	
-	ip addr flush dev "$wifidev"
-
+  echo "Shutting Down Hotspot"
+  ifdown "$wifidev"
+  systemctl stop hostapd
+  systemctl stop dnsmasq
+  systemctl mask dnsmasq
+  systemctl mask hostapd
+  echo "Hotspot down"
+  ip addr flush dev "$wifidev"
+  ifup "$wifidev"
+  dhcpcd  -n "$wifidev" >/dev/null 2>&1
 }
 
-#/////////////////////////////////////////////////////////////////////////////////////
-# Check if Wifi is up
-#/////////////////////////////////////////////////////////////////////////////////////
 ChkWifiUp()
 {
+  echo "Checking WiFi connection ok"
+  sleep 5 #give time for connection to be completed to router
+  ip_to_mqtt
 
-	echo "[$(date +'%H:%m:%S')] Checking WiFi connection with $ssidChk" >> /var/log/autohotspot.log
-	
-	sleep 5
-	
-	checkwifi="$(iw $wifidev link | grep 'Connected to' | wc -l)"
-	
-	if [ $checkwifi -eq 0 ]; then
-		echo "[$(date +'%H:%m:%S')] Wifi failed to connect, falling back to Hotspot." >> /var/log/autohotspot.log
-		createAdHocNetwork
-	else
-		echo "[$(date +'%H:%m:%S')] Connected to $ssidChk" >> /var/log/autohotspot.log
-		ntpdate -u ch.pool.ntp.org
-		
-		if grep static /etc/network/interfaces; then 
-			pkill -f "dhclient"
-		fi
-	fi
-
+  if ! wpa_cli -i "$wifidev" status | grep 'ip_address' >/dev/null 2>&1 ; then #Failed to connect to wifi
+    echo 'Wifi failed to connect, falling back to Hotspot.'
+    wpa_cli terminate "$wifidev" >/dev/null 2>&1
+    createAdHocNetwork
+  fi
 }
 
-#/////////////////////////////////////////////////////////////////////////////////////
-# Connect to Wifi
-#/////////////////////////////////////////////////////////////////////////////////////
-function connect_wifi {
 
-	ip link set dev "$wifidev" up
-	wpa_supplicant -B -i "$wifidev" -c /etc/wpa_supplicant/wpa_supplicant.conf >/dev/null 2>&1
-
-	if grep dhcp /etc/network/interfaces; then 
-		dhclient "$wifidev"
-	fi
-
-	echo "[$(date +'%H:%m:%S')] Wifi connected" >> /var/log/autohotspot.log
-	
-}
-
-#/////////////////////////////////////////////////////////////////////////////////////
-# Disconnect Wifi
-#/////////////////////////////////////////////////////////////////////////////////////
-function disconnect_wifi {
-
-	ip link set dev "$wifidev" down
-	wpa_cli terminate >/dev/null 2>&1
-	ip addr flush "$wifidev"
-	rm -r /var/run/wpa_supplicant >/dev/null 2>&1
-	echo "[$(date +'%H:%m:%S')] Wifi disconnected" >> /var/log/wmod.log
-	
-}
-
-#/////////////////////////////////////////////////////////////////////////////////////
-# Find SSIDs in Range
-#/////////////////////////////////////////////////////////////////////////////////////
 FindSSID()
 {
   #Check to see what SSID's
@@ -128,112 +85,94 @@ FindSSID()
 
   until [ $i -eq 1 ] ; do #wait for wifi if busy, usb wifi is slower.
     ssidreply=$((iw dev "$wifidev" scan ap-force | egrep "^BSS|SSID:") 2>&1) >/dev/null 2>&1 
-    echo "[$(date +'%H:%m:%S')] SSid's in range: " $ssidreply >> /var/log/autohotspot.log
-    echo "[$(date +'%H:%m:%S')] Device Available Check try " $j >> /var/log/autohotspot.log
+    echo "SSid's in range: " $ssidreply
+    echo "Device Available Check try " $j
 
     if (($j >= 10)); then #if busy 10 times goto hotspot
-      echo "[$(date +'%H:%m:%S')] Device busy or unavailable 10 times, going to Hotspot" >> /var/log/autohotspot.log
+      echo "Device busy or unavailable 10 times, going to Hotspot"
       ssidreply=""
       i=1
-      sleep 1
+      # sleep 1
 
     elif echo "$ssidreply" | grep "No such device (-19)" >/dev/null 2>&1; then
-      echo "[$(date +'%H:%m:%S')] No Device Reported, try " $j >> /var/log/autohotspot.log
+      echo "No Device Reported, try " $j
       NoDevice
 
     elif echo "$ssidreply" | grep "Network is down (-100)" >/dev/null 2>&1 ; then
-      echo "[$(date +'%H:%m:%S')] Network Not available, trying again" $j >> /var/log/autohotspot.log
+      echo "Network Not available, trying again" $j
 
       if (($j == 1)); then # try bringing up wlan0 once
-		ip link set dev "$wifidev" up
+        ifup "$wifidev"
       fi
 
       j=$((j + 1))
-      sleep 2
+      # sleep 2
 
     elif echo "$ssidreplay" | grep "Read-only file system (-30)" >/dev/null 2>&1 ; then
-      echo "[$(date +'%H:%m:%S')] Temporary Read only file system, trying again" >> /var/log/autohotspot.log
+      echo "Temporary Read only file system, trying again"
       j=$((j + 1))
-      sleep 2
+      # sleep 2
 
     elif ! echo "$ssidreply" | grep "resource busy (-16)" >/dev/null 2>&1 ; then
-      echo "[$(date +'%H:%m:%S')] Device Available, checking SSid Results" >> /var/log/autohotspot.log
+      echo "Device Available, checking SSid Results"
       i=1
 
     else #see if device not busy in 2 seconds
-      echo "[$(date +'%H:%m:%S')] Device unavailable checking again, try " $j >> /var/log/autohotspot.log
+      echo "Device unavailable checking again, try " $j
       j=$((j + 1))
-      sleep 2
+      # sleep 2
     fi
   done
 
   for ssid in "${ssidsmac[@]}" ; do
     if (echo "$ssidreply" | grep "$ssid") >/dev/null 2>&1 ; then #Valid SSid found, passing to script
-      echo "[$(date +'%H:%m:%S')] Valid SSID Detected, assesing Wifi status" >> /var/log/autohotspot.log
+      echo "Valid SSID Detected, assesing Wifi status"
       ssidChk=$ssid
       return 0
     else #No Network found, NoSSid issued"
-      echo "[$(date +'%H:%m:%S')] No SSID found, assessing WiFi status" >> /var/log/autohotspot.log
+      echo "No SSID found, assessing WiFi status"
       ssidChk='NoSSid'
     fi
   done
 }
 
-#/////////////////////////////////////////////////////////////////////////////////////
-# No Wifi Device
-#/////////////////////////////////////////////////////////////////////////////////////
 NoDevice()
 {
   #if no wifi device,ie usb wifi removed, activate wifi so when it is
   #reconnected wifi to a router will be available
-  echo "[$(date +'%H:%m:%S')] No wifi device connected" >> /var/log/autohotspot.log
+  echo "No wifi device connected"
   wpa_supplicant -B -i "$wifidev" -c /etc/wpa_supplicant/wpa_supplicant.conf >/dev/null 2>&1
   exit 1
 }
-
-#/////////////////////////////////////////////////////////////////////////////////////
-# Main
-#/////////////////////////////////////////////////////////////////////////////////////
 
 FindSSID
 
 #Create Hotspot or connect to valid wifi networks
 if [ "$ssidChk" != "NoSSid" ] ; then
   if systemctl status hostapd | grep "(running)" >/dev/null 2>&1 ; then #hotspot running and ssid in range
-  
     KillHotspot
-	echo "[$(date +'%H:%m:%S')] Hotspot Deactivated, Bringing Wifi Up" >> /var/log/autohotspot.log
-	connect_wifi
-	echo "[$(date +'%H:%m:%S')] Connecting to Wifi" >> /var/log/autohotspot.log
-	ChkWifiUp
-
+    echo "Hotspot Deactivated, Bringing Wifi Up"
+    ifup "$wifidev"
+    ChkWifiUp
   elif { wpa_cli -i "$wifidev" status | grep 'ip_address'; } >/dev/null 2>&1 ; then #Already connected
-
-    echo "[$(date +'%H:%m:%S')] Wifi already connected to a network" >> /var/log/autohotspot.log
-
+    echo "Wifi already connected to a network"
   else #ssid exists and no hotspot running connect to wifi network
-
-    echo "[$(date +'%H:%m:%S')] Connecting to the WiFi Network" >> /var/log/autohotspot.log
-	connect_wifi
-	ChkWifiUp
-
+    echo "Connecting to the WiFi Network"
+    ifup "$wifidev"
+    ChkWifiUp
   fi
 
 else #ssid or MAC address not in range
     if systemctl status hostapd | grep "(running)" >/dev/null 2>&1 ; then
-
-      echo "[$(date +'%H:%m:%S')] Hostspot already active" >> /var/log/autohotspot.log
-
+      echo "Hostspot already active"
     elif { wpa_cli status | grep "$wifidev"; } >/dev/null 2>&1 ; then
-		
-	  echo "[$(date +'%H:%m:%S')] Wifi running, activating Hotspot" >> /var/log/autohotspot.log
-	  disconnect_wifi
+      echo "Cleaning wifi files and Activating Hotspot"
+      ifdown "$wifidev"
+      wpa_cli terminate >/dev/null 2>&1
+      ip addr flush "$wifidev"
+      rm -r /var/run/wpa_supplicant >/dev/null 2>&1
       createAdHocNetwork
-
-    else
-
-	   echo "[$(date +'%H:%m:%S')] No SSID, activating hotspot" >> /var/log/autohotspot.log
+    else #"No SSID, activating Hotspot"
        createAdHocNetwork
-
     fi
 fi
diff --git a/usr/local/nanohome/bin/devmgmt b/usr/local/nanohome/bin/devmgmt
--- a/usr/local/nanohome/bin/devmgmt
+++ b/usr/local/nanohome/bin/devmgmt
@@ -1,16 +1,26 @@
 #!/bin/bash
-#/////////////////////////////////////////////////////////////////////////////////////
-# Device Manager for NanoHome - manages MQTT Devices on Grafana Dashboards
-#/////////////////////////////////////////////////////////////////////////////////////
+# devmgmt - manages MQTT devices on grafana dashboards
 
-# Catch Parameters
+if [ -z "$1" ]; then
+	
+	echo "----------------------------------------------------------"
+	echo "Zu wenig Argumente"
+	echo "Usage: devmgmt add|remove sn description device devicetype"
+	echo "----------------------------------------------------------"
+	echo
+	
+	exit 1
+	
+fi
+
+# parameter
 sn="$2"
 desc="$3"
 device="$4"
 devicetype="$5"
 random="$(date +%s)"
 
-# Settings
+# settings
 home_uid="XieEaLmRk"
 devmgr_uid="Uhzl9yRgk"
 zsp_uid="_H3fwdmRz"
@@ -18,7 +28,7 @@ settings_uid="sYOGRUiRz"
 api_key="eyJrIjoiWk9YZDVmbGhRMkpmYjdsT3h3VjhSVjR5cXlwZUh1d3MiLCJuIjoiY3JlYXRlX2VsZW1lbnRzIiwiaWQiOjF9"
 template_folder="/usr/local/nanohome/templates"
 
-# Help Functions
+# functions
 get_dashboard () {
 	
 	uid="$1"
@@ -35,199 +45,174 @@ add_json_options () {
 
 update_dashboard () {
 
-	curl -X POST --insecure -H "Authorization: Bearer $api_key" -H "Content-Type: application/json" -d @/tmp/merge_panel_final.json http://localhost:3001/api/dashboards/db > /dev/null 2>&1
+	curl -X POST --insecure -H "Authorization: Bearer $api_key" -H "Content-Type: application/json" -d @/tmp/merge_panel_final.json http://localhost:3001/api/dashboards/db
 }
 
-#/////////////////////////////////////////////////////////////////////////////////////
-# Show Devices
-#/////////////////////////////////////////////////////////////////////////////////////
-show_devices () {
-
-	msg="$(cat /usr/local/nanohome/devlist | awk -F':' '{printf "<font color='hotpink'>"$2 ":</font> " $1 "<br>"}')"
-	statusmsg "Geräteliste" "white" "" "" "$msg" "white"
-	exit 0
-
-}
-
-#/////////////////////////////////////////////////////////////////////////////////////
-# Add Device
-#/////////////////////////////////////////////////////////////////////////////////////
-add_device () {
-
-	# add device to devlist
-	echo -e "$sn:$desc:$device:$devicetype" >> /usr/local/nanohome/devlist
+err_exit () {
 	
-	# Fill Dropdown in Devicemanager Dashboard //////////////////////////////////////////////////
+	statusmsg "Error" "red" "" "" "" "" "Zu wenig Parameter definiert \nUsage: devmgmt add|remove sn description device devicetype" "white"
+	
+	exit 1
+}
+
+# show devices
+if [ "$1" = "show" ]; then
+	
+	msg=$(cat /usr/local/nanohome/devlist | awk -F':' '{printf "<font color='hotpink'>"$2 ":</font> " $1 "<br>"}')
+
+	statusmsg "Geräteliste" "white" "" "" "" "" "$msg" "white"
+
+	exit 0
+	
+fi
+
+# add device
+if [ "$1" = "add" ]; then
+
+	if  [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ] || [ -z "$5" ]; then
+	
+		err_exit
+		
+	fi
+	
+	# add device to devlist
+	echo -e "\n$sn:$desc" >> /usr/local/nanohome/devlist
+	
+	# get devicemanager dashboard & make it readable
 	get_dashboard "$devmgr_uid"
 	jq . /tmp/merge_panel_temp.json > /tmp/merge_panel_output.json
-	sed -i 's#name=\\"nanolist\\">#name=\\"nanolist\\">\\r\\n\\t\\t\\t\\t\\t\\t<option value=\\"http://'$sn'.nano.lan\\">'"$desc"'</option>#g' /tmp/merge_panel_output.json
+
+	# add new option to dropdown
+	sed -i 's#name=\\"nanolist\\">#name=\\"nanolist\\">\\r\\n<option value=\\"'$sn'.nnao.lan\\">'$desc'</option>#g' /tmp/merge_panel_output.json
 
 	add_json_options
 	update_dashboard
 
 	# cleanup
 	rm /tmp/merge_panel_*
-	
-	# Fill Dropdown in Settings Dashboard //////////////////////////////////////////////////
-	get_dashboard "$settings_uid"
-	jq . /tmp/merge_panel_temp.json > /tmp/merge_panel_output.json
-	sed -i 's#name=\\"nanolist\\">#name=\\"nanolist\\">\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<option value=\\"'$sn'\\">'"$desc"'</option>#g' /tmp/merge_panel_output.json
-	
-	add_json_options
-	update_dashboard
-	
-	# cleanup
-	rm /tmp/merge_panel_*
-	
-	# add home-dash element if device is a switch or a rollo
-	if [ "$devicetype" == "switch" ] || [ "$devicetype" == "roller" ] || [ "$devicetype" == "shutter" ]; then
+
+
+	# add specific elements if device is a switch
+	if [ "$devicetype" == "switch" ]; then
 		
-		
-		# Create Button on Home Dashboard //////////////////////////////////////////////////
-		# create new element from template
-		if [ "$devicetype" == "switch" ]; then
-			cp $template_folder"/"$device"_switch.json.template" "/tmp/merge_panel_input.json"
-		elif [ "$devicetype" == "roller" ]; then
-			cp $template_folder"/"$device"_roller.json.template" "/tmp/merge_panel_input.json"
-		elif [ "$devicetype" == "shutter" ]; then
-			cp $template_folder"/"$device"_shutter.json.template" "/tmp/merge_panel_input.json"
-		fi
-		
-		sed -i 's/_DEVID_/'$sn'/g'  /tmp/merge_panel_input.json
-		sed -i 's/_DESCRIPTION_/'"$desc"'/g'  /tmp/merge_panel_input.json
-		sed -i 's/_RAND_/'$random'/g'  /tmp/merge_panel_input.json
+		## button on home dashboard
+		# create new button from template
+		cp $template_folder"/"$device"_switch.json.template" "/tmp/merge_panel_input.json"
+
+		sed -i "s/_DEVID_/"$sn"/g"  /tmp/merge_panel_input.json
+		sed -i "s/_DESCRIPTION_/"$desc"/g"  /tmp/merge_panel_input.json
+		sed -i "s/_RAND_/"$random"/"  /tmp/merge_panel_input.json
 		
 		get_dashboard "$home_uid"
 
 		# merge new Button into Dashboard
 		jq --argjson panel "$(</tmp/merge_panel_input.json)" '.dashboard.panels += [$panel]' /tmp/merge_panel_temp.json > /tmp/merge_panel_output.json
 		add_json_options
+		
 		update_dashboard
 		
 		# cleanup
 		rm /tmp/merge_panel_*
 		
-	fi
-	
-	# Add Switch specific Elements //////////////////////////////////////////////////
-
-	if [ "$devicetype" == "switch" ] || [ "$devicetype" == "roller" ] || [ "$devicetype" == "shutter" ]; then
 		
-		# Dropdown on Timer Dashboard
-		
+		## dropdown on timer dashboard
 		# get timer dashboard & make it readable
 		get_dashboard "$zsp_uid"
 		jq . /tmp/merge_panel_temp.json > /tmp/merge_panel_output.json
 		
-		# add new option to timer dropdown
-		sed -i 's#name=\\"nanolist_timer\\">#name=\\"nanolist_timer\\">\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<option value=\\"'$sn'\\">'"$desc"'</option>#g' /tmp/merge_panel_output.json
-
-		# add new option to multiswitch dropdown
-		sed -i 's#Wenn...</option>">#Wenn...</option>\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<option value=\\"'$sn'\\">'"$desc"'</option>#g' /tmp/merge_panel_output.json
-		sed -i 's#Dann...</option>">#Dann...</option>\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<option value=\\"'$sn'\\">'"$desc"'</option>#g' /tmp/merge_panel_output.json
-		
-		# add new option to standbykiller dropdown
-		if [ "$devicetype" == "switch" ]; then
-		
-			sed -i 's#name=\\"nanolist_stbykill\\">#name=\\"nanolist_stbykill\\">\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<option value=\\"'$sn'\\">'"$desc"'</option>#g' /tmp/merge_panel_output.json
-		
-		fi
+		# add new option to dropdown
+		sed -i 's#name=\\"nanolist\\">#name=\\"nanolist\\">\\r\\n<option value=\\"'$sn'\\">'$desc'</option>#g' /tmp/merge_panel_output.json
 		
 		add_json_options
 		update_dashboard
 		
 		# cleanup
 		rm /tmp/merge_panel_*
-	
+		
+		## dropdowns in ettings dashboard
+		# Ggt Settings Dashboard & make it readable
+		get_dashboard "$settings_uid"
+		jq . /tmp/merge_panel_temp.json > /tmp/merge_panel_output.json
+		
+		# add new option to dropdown
+		sed -i 's#name=\\"nanolist\\">#name=\\"nanolist\\">\\r\\n<option value=\\"'$sn'\\">'$desc'</option>#g' /tmp/merge_panel_output.json
+		
+		add_json_options
+		update_dashboard
+		
+		# cleanup
+		rm /tmp/merge_panel_*
+		
 	fi
 	
 	# message
-	statusmsg "Device Manager: " "white" "" "" "$desc:" "hotpink" " $sn hinzugefügt" "white"
+	
+	statusmsg "Device Manager" "white" "$desc:" "hotpink" " Gerät $sn hinzugefügt" "white"
 	
 	exit 0
+	
+fi
 
-}
-
-#/////////////////////////////////////////////////////////////////////////////////////
-# Remove Device
-#/////////////////////////////////////////////////////////////////////////////////////
-remove_device () {
-
-	# remove services and timers
-	cronman remove "$sn"
-	multiswitch remove "$sn"
-	standbykiller remove "$sn"
+# remove device
+if [ "$1" = "remove" ]; then
+	
+	if  [ -z "$2" ] || [ -z "$3" ]; then
+	
+		err_exit
+		
+	fi
 	
 	# remove device from devlist
 	sed -i '/'$sn'/d' /usr/local/nanohome/devlist
 	
-	# Remove from Devicemanager Dashboard //////////////////////////////////////////////////
+	## remove from device manager dashboard
+	# get devicemanager dashboard & make it readable
 	get_dashboard "$devmgr_uid"
 	jq . /tmp/merge_panel_temp.json > /tmp/merge_panel_output.json
-	sed -i 's#\\r\\n\\t\\t\\t\\t\\t\\t<option value=\\"http://'$sn'.nano.lan\\">'"$desc"'</option>##g' /tmp/merge_panel_output.json
-	
+
+	# remove option from dropdown
+	sed -i 's#<option value=\\"'$sn'.nano.lan\\">'$desc'</option>\\r\\n##g' /tmp/merge_panel_output.json
+
 	add_json_options
-	update_dashboard
-	
+	update_dashboard		
+
 	# cleanup
 	rm /tmp/merge_panel_*
 
-	# Remove from Settings Dashboard //////////////////////////////////////////////////	
-	get_dashboard "$settings_uid"
-	jq . /tmp/merge_panel_temp.json > /tmp/merge_panel_output.json
-	sed -i 's#\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<option value=\\"'$sn'\\">'"$desc"'</option>##g' /tmp/merge_panel_output.json
-	
-	add_json_options
-	update_dashboard
-	
-	# cleanup
-	rm /tmp/merge_panel_*
-	
+	## remove from timer dashboard
+	# get timer dashboard & make it readable
 	get_dashboard "$zsp_uid"
 	jq . /tmp/merge_panel_temp.json > /tmp/merge_panel_output.json
-
-	# Remove from Tettings Dashboard //////////////////////////////////////////////////
-	# if device found
-	if cat /tmp/merge_panel_output.json | grep "$sn" > /dev/null 2>&1 ; then
-		
-		sed -i 's#\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<option value=\\"'$sn'\\">'"$desc"'</option>##g' /tmp/merge_panel_output.json
 	
-		add_json_options
-		update_dashboard
-		
-	fi
+	# remove option from dropdown
+	sed -i 's#<option value=\\"'$sn'\\">'$desc'</option>\\r\\n##g' /tmp/merge_panel_output.json
+	
+	<option value=\"TEMP\">TEMP</option>\r\n
+	
+	add_json_options
+	update_dashboard
 
+	# cleanup
+	rm /tmp/merge_panel_*
+
+	## remove from settings dashboard
+	# get settings dashboard & make it readable
+	get_dashboard "$settings_uid"
+	jq . /tmp/merge_panel_temp.json > /tmp/merge_panel_output.json
+	
+	# remove option to dropdown
+	sed -i 's#<option value=\\"'$sn'\\">'$desc'</option>\\r\\n##g' /tmp/merge_panel_output.json
+	
+	add_json_options
+	update_dashboard
+	
 	# cleanup
 	rm /tmp/merge_panel_*
 	
 	# message
-	statusmsg "Device Manager: " "white" "" "" "$desc:" "hotpink" " $sn gelöscht <br> Button auf Home-Dashboard manuell löschen" "white"
+	
+	statusmsg "Device Manager" "white" "$desc:" "hotpink" " Gerät $sn gelösch\nButton auf Home manuell löschent" "white"
 	
 	exit 0
-
-}
-
-#/////////////////////////////////////////////////////////////////////////////////////
-# Main
-#/////////////////////////////////////////////////////////////////////////////////////
-if [ "$1" = "show" ]; then
-	
-	show_devices
-
-elif [ "$1" = "add" ] && [ ! -z "$sn" ] && [ ! -z "$desc" ] && [ ! -z "$device" ] && [ ! -z "$devicetype" ] && [ ! "$sn" = "Device ID" ] && [ ! "$desc" = "Bezeichnung" ]; then
-
-	add_device
-
-elif [ "$1" = "remove" ] && [ ! -z "$sn" ] && [ ! -z "$desc" ]; then
-
-	remove_device
-
-#/////////////////////////////////////////////////////////////////////////////////////
-# Err Exit
-#/////////////////////////////////////////////////////////////////////////////////////
-else
-
-	errmsg "Error" "Eingabe prüfen"
-	exit 1
 
 fi
